### ISSUE TITLE
How does plausible_head_csp suppose to work

### ISSUE THREAD

**Issue by madanyang** [divinerites/plausible-hugo#11]
Either the code is wrong or the documentation is not clear and finally as the last option I need something stronger than coffee.

I am not using netlify so all things related to netlify does not qualify for my case. I am expecting to get the code to produce the following

```
<link rel="preconnect" href="https://myplausible.hosting.domain">
  <script defer data-domain="example.com"
          script-src="https://myplausible.hosting.domain"
          connect-src="https://myplausible.hosting.domain"
          src="https://myplausible.hosting.domain/js/plausible.js" ></script>
```

but I can't seem to get he script-src and connect-src printed in the plausible script with the following

```
{{- with .Site.Params.plausible -}}
  {{ printf "  script-src "  | safeHTML }}{{- partial "plausible_csp.html" . }}
  {{ printf "  connect-src " | safeHTML }}{{- partial "plausible_csp.html" . }}
  {{- partial "plausible_head.html" . -}}
  {{- end -}}
```
What am I missing

**Comment by divinerites** [comment]
Hello,

Well, the `plausible_csp.html` is supposed to work with ... CSP ...

The `plausible_head_csp.html` is just an internal partial, and I don't think it is on the user doc. Just don't use it.
As you are not using Netlify you should see this in your code.

```
<!-- If you are using Content-Security-Policy, do not forget to add this code to your CSP :
 script-src 'unsafe-inline' https://plausible.io
 connect-src 'unsafe-inline' https://plausible.io
 or just add the partial 'plausible_csp.html' to those 2 csp directives in your 'index.headers' file
 -->
```

The `plausible_csp.html` is on the documentation but the use case is for your `headers`. if you are using CSP.

```
/*
  X-Frame-Options: DENY
  X-XSS-Protection: 1; mode=block
  X-Content-Type-Options: nosniff
  Referrer-Policy: no-referrer
  Content-Security-Policy: script-src 'self' 'unsafe-inline' {{ partial "plausible_csp.html" . }} https://cdn.jsdelivr.net https://wubook.net https://static.wubook.net; base-uri 'none'

```

The code you are trying to achieve doesn't seems related to CSP.

**Comment by madanyang** [comment]
Hawaii is a nice option thanks, closing the issue
