### ISSUE TITLE
Custom tracking script name

### ISSUE THREAD

**Issue by FarisZR** [divinerites/plausible-hugo#12]
Hello,
thanks for the awesome project!,

can you add the ability to customize the tracking script's name?
I use nginx rewrite to get past ad-blockers, and it would be useful if this component can support custom script names.

**Comment by divinerites** [comment]
I don't understand what you need. 
do you have an example for your use case ??

**Comment by FarisZR** [comment]
I meant a way to change the standard script name from, plausible.js, to something different.

For example, https://server.domain.com/js/plausible.js > https://server.domain.com/js/pls1.js.

Its the same script, just a different name.

Its used to get past Ad-blockers, more details here:
https://plausible.io/docs/proxy/introduction
https://plausible.io/docs/proxy/guides/nginx

**Comment by divinerites** [comment]
Sorry but still do not understand.
This project is usefull **if** you use the plausible script.

If you have control on your ngnix, why don't you make what you want/need on the rewrite part ??

I do not see how my module can help you in the ngnix use case.

**Comment by divinerites** [comment]
I think that renaming the script is the job for the `proxy` part and not for this module.

**Comment by FarisZR** [comment]
I know, what i am asking is for this module, to use the new and proxied script name.
Not the standrad name.

Instead of calling https://plausible.server.com/js/pausible.js, it would call the custom script name specified by the user, like https://plausible.server.com/js/newname.js

**Comment by divinerites** [comment]
> I know, what i am asking is for this module, to use the new and proxied script name. Not the standrad name. Instead of calling [plausible.server.com/js/pausible.js](https://plausible.server.com/js/pausible.js), it would call the custom script name specified by the user, like [plausible.server.com/js/newname.js](https://plausible.server.com/js/newname.js)

Yes I understand.

This is why i'm telling you that this is the work for the `proxy`/ `rewrite` part. And not this module.

Just take the `proxy_netlify.html` idea and code this same principle in your ngnix conf.
I think it is just this.

When you've done it I can add your ngnix conf to the project.

**Comment by divinerites** [comment]
I have **NO WAY** to do this in the module.

This only can be done on the proxy side (netlify or ngnix, apache, whatever)

**Comment by divinerites** [comment]
And I do think that if you still, call from `plausible.server.com` this **will not** bypass the adblockers.

Whatever the script name is.

**Comment by FarisZR** [comment]
I have already setup a rewrite, i already have a custom script name.

This module by default, uses the default script name by Plausible (/js/plausible.js).

I want to make the module use the custom script name, which I already had set up with Nginx.

So instead of calling /js/plausible.js, it will call the new rewritten script name specified by the user.

I'm not asking for the module to do the rewrite for me, I already set it up, I want the module to use it.

**Comment by divinerites** [comment]
OK. I saw that you have a clean way of doing it :
`<script async defer data-domain="aosus.org" src="https://pa.aosus.org/js/pls4.js"></script>`


But I'm really sorry ... i just do not understand the point.

My module *JUST* call the  right script from `plausible.io` according to variables.
Just that.

**AFTER** this, and because I use Netlify I rewrite the origin+script name for something else in my netlify conf. 
And I provide as a bonus a partial for this : `proxy_netlify.html`

In your case if I use the domain name `pa.aosus.org` I would have written this:

```
# Redirects for plausible.io & github.com/divinerites/plausible-hugo
{{- if site.Params.plausible.outbound_link }}
/js/s/pls4.js https://plausible.io/js/plausible.outbound-links.js 200
{{- else }}
/js/s/pls4.js https://plausible.io/js/plausible.js 200
{{- end }}
/api/event https://plausible.io/api/event 200
```

And this would generate your ``<script async defer data-domain="aosus.org" src="https://pa.aosus.org/js/pls4.js"></script>` or so.

**Comment by divinerites** [comment]
You are asking for something that I (or anyone) can't do inside this module.

**Comment by FarisZR** [comment]
Would the module use /js/s/pls4.js instead of directly conneting to plausible?

**Comment by divinerites** [comment]
> Would the module use /js/s/pls4.js instead of directly conneting to plausible?

Sorry, but I think you're missing something on the way all this works.

It is the other way **YOU** rename the plausible script in whatever you want.

**Comment by FarisZR** [comment]
The module uses the standard script names,
my question is about a way to change the name of the script used in the module
from /js/plausib.xxx.js
to a custom one, like /js/pa1.js

Also this projects seems to not support Self-hosted Plausible instances, is that right?

**Comment by divinerites** [comment]
> about a way to change the name of the script used in the module

I'm still far away to understand why you still looking for this rename thing in THIS module, as it is a EXTERNAL job to do.
Still puzzled with your request and the lack of trying to do this outside the script.

> Also this projects seems to not support Self-hosted Plausible instances, is that right?

I do not use it myself, but we have a [self hosting option](https://github.com/divinerites/plausible-hugo#5---self-hosting)

```toml
[params.plausible]
   selfhosted_domain = "myplausible.example.com"  # Self-hosted plausible domain
```

**Comment by divinerites** [comment]
If you look at this partial [plausible_redirects_netlify.html](https://github.com/divinerites/plausible-hugo/blob/master/layouts/partials/plausible_redirects_netlify.html), it is just something created for netlify users, but this partial is OUTSIDE the real module.

Just do the same with your context.

In short : **I WILL NOT** change the name in this module. **NOT**.

**Comment by FarisZR** [comment]
That comment was an email that was probably stuck on sending a long time ago.
Sorry, to re-open the issue!

**Comment by steve-winter** [comment]
I have made the change that I think you want, and was certainly what I was after, here; https://github.com/steve-winter/plausible-hugo 

New config param to enable changing the JS filename to whatever I want.

**Comment by divinerites** [comment]
Thanks see [my comment](https://github.com/steve-winter/plausible-hugo/commit/bb859c4101684c78a4cb583f134eec26e177d203#commitcomment-86548885).

Reopening for now

**Comment by divinerites** [comment]
OK. Got your comments on the PR.

So we all agree (@steve-winter & @FarisZR) :

1. The option for changing the script name is concernin g self-hosting use case.
2. In all other cases (using the polausible.io service), changing script name only can be done thru proxy rewrite.
  - This is outside the scope of this module.
  - We can add some extra partial for that if someone provide the code for the proxy. 
    - The example for this is the `plausible_redirects_netlify.html` exytra script
    - You could name it `plausible_redirects_MYPROXY.html` with `MYPROXY` being the proxy real name.
    
  Are we all ok with this ? If yes i will make the change base on your PR.

**Comment by benoitmartin88** [comment]
Hi, thanks for your work.
It would be great if I could customize the tracking script name.
Are you planning on merging @steve-winter's fix ?
