### ISSUE TITLE
Alternative proxy options

### ISSUE THREAD

**Issue by olliejudge** [divinerites/plausible-hugo#18]
I might be being a bit daft but is there a way of enabling proxying without any Netlify options. I use Render and the rewrites are done through the dashboard. Is there a way of easily setting an empty path that gets rewritten or would it require a fork to change behaviour?

**Comment by divinerites** [comment]
Hello, well it should be straightforward with plausible Doc.

Redirect those in your dashboard:

/misc/js/script.js 
to https://plausible.io/js/plausible.outbound-links.js with code 200

Or /misc/js/script.js to https://plausible.io/js/plausible.js with code 200


Plus 


/misc/api/event to https://plausible.io/api/event with 200

You get the Idea ...
