### ISSUE TITLE
Tracking script name should reflect the original plausible documentation

### ISSUE THREAD

**Issue by madanyang** [divinerites/plausible-hugo#20]
[according to the documentation ](https://plausible.io/docs/plausible-script)and the actual code provided by plausible the tracking script name is not anymore plausible 

```
<script defer data-domain="yourdomain.com" src="https://plausible.io/js/script.js"></script>

``` 

This module is still using the old approach of using plausible.js which is problematic due to various blockers

**Comment by ghk-arolla** [comment]
Thanks. I will look at those changes.

**Comment by divinerites** [comment]
Updated version 1.19.0.

@madanyang let me know if it works fine.

**Comment by divinerites** [comment]
> This module is still using the old approach of using plausible.js which is problematic due to various blockers

I really advice for using proxy. Will be much better that even the stock `script.js` name.

I provide automatic proxy redirect for Netlify but you can do the same for any other hosting by yourself.

**Comment by madanyang** [comment]
> Updated version 1.19.0.
> 
> @madanyang let me know if it works fine.

Thanks works with small issues even though proxy_netlify is false the module is creating an unneeded/unnecessary _redirects_do_not_use file in the root directory.

**Comment by madanyang** [comment]
> > This module is still using the old approach of using plausible.js which is problematic due to various blockers
> 
> I really advice for using proxy. Will be much better that even the stock `script.js` name.
> 
> I provide automatic proxy redirect for Netlify but you can do the same for any other hosting by yourself.

self hosted version so I don't see any reason for a need to proxy.

**Comment by divinerites** [comment]
> proxy_netlify is false the module is creating an unneeded/unnecessary _redirects_do_not_use file in the root directory.

I know. Hence the "do_not_use" on name 😸

**Comment by divinerites** [comment]
> self hosted version so I don't see any reason for a need to proxy.

yes. I thought you were hosted.

Cool. Closing this and thanks for the report about this change.
