### ISSUE TITLE
Find a way to issue the WARN hint for gitstar only once for multilingual sites

### ISSUE THREAD

**Issue by divinerites** [divinerites/plausible-hugo#5]
The console message is issued for each site.Language.

We need to find a way to issue it only once

**Comment by regisphilibert** [comment]
You could check if `eq site.Lang site.Sites.First.Lang` or any other way to make sure you are on the "first" site before issuing the warning.

**Comment by divinerites** [comment]
Solved by https://github.com/divinerites/plausible-hugo/commit/16fcc6eb8497bc71198377a531fedbe895f92a2e

Thanks a lot @regisphilibert
