### ISSUE TITLE
Use baseURL as configured Plausible domain?

### ISSUE THREAD

**Issue by ringods** [divinerites/plausible-hugo#7]
Hello,

I host my static site on Netlify. When doing branch previews, I use this as the build command:

```
hugo --buildFuture -b $DEPLOY_PRIME_URL
```

Netlify provides the value for `DEPLOY_PRIME_URL` as my site baseURL. Is there any way I can use this value as the configured Plausible domain? I would like any preview hits not be added to my regular site statistics.

**Comment by divinerites** [comment]
But you can try some thing like 

```
{{ if "your env variable" }} 
do the plausible stuff
{{ end }}
