### ISSUE TITLE
Add better proxy request support for AWS Cloudfront hosted sites

### ISSUE THREAD

**Issue by sujal** [divinerites/plausible-hugo#9]
I've setup my blog using Cloudfront and S3. I ended up using the `custom_js_domain` option to get this to work for my site, using a cloudfront function to rewrite the URL from `index.js` to `plausible.js`. We need a `proxy_netlify` option that is better suited for AWS. Open to other ideas, I can submit a patch if there's a sense of how best to implement this.

**Comment by divinerites** [comment]
And do not change the `proxy_netlify`. Just add a new `proxy_aws`  option.

**Comment by sujal** [comment]
Just getting back from some travel. Will take a look at this soon. Thanks for the response.

**Comment by divinerites** [comment]
Can I close this issue @sujal  ??

**Comment by sujal** [comment]
You can close it. I joined a startup right after that comment, just have been too busy. I will submit a patch when I have time to work on this again.

**Comment by divinerites** [comment]
Thanks a lot @sujal and good luck with your new job.
